### ISSUE TITLE
Request to remove no-await-in-loop eslint rule

### ISSUE THREAD

**Issue by Davidster** [ClipboardHealth/core-utils#9]
Consider the following code which I encountered when writing [this PR](https://github.com/ClipboardHealth/clipboard-health/pull/13892/files):

```ts
const people = [
  { firstName: "David", lastName: "Huculak", isAdmin: false },
  { firstName: "John", lastName: "Smith", isAdmin: false },
  { firstName: "David", lastName: "Smith", isAdmin: false },
  { firstName: "CBH Engineer", isAdmin: true },
];

const getCachedAge = memoize(async (name: string) => await fetchAge(name));

const allowedPeople = [];
for (const person of people) {
  if (person.isAdmin) {
    allowedPeople.push(person);
    continue;
  }

  const age = await getCachedAge(person.firstName);
  if (age > 30) {
    allowedPeople.push(person);
  }
}

return allowedPeople;
```

Currently in cbh, the `no-await-in-loop` rule would report an error for the line `const age = await getCachedAge(person.firstName);`. But I think this code is quite reasonable to write as-is. The [eslint docs](https://eslint.org/docs/latest/rules/no-await-in-loop#when-not-to-use-it) suggest that in such scenarios we should just disable the lint for this particular line. In my opinion this limitation greatly reduces the value of the lint and mostly just makes it annoying to write sequential async code (which you sometimes want to do), as the programmer has to jump to the eslint docs just to learn that the workaround is to disable the rule. 

Could we disable it or change it from "error" to "warn"?

**Comment by Davidster** [comment]
@therockstorm any thoughts? 

I believe @pgbezerra expressed that would rather keep the `no-await-in-loop` because he believes that the vast majority of such cases should be rewritten with concurrency.

**Comment by therockstorm** [comment]
I agree with @pgbezerra. If you know what you're doing and _really_ want sequential async code, ignore the rule. This is an exception to the rule of favoring concurrency.

**Comment by Davidster** [comment]
Sounds reasonable enough. I'm still kinda on the fence because it feels like we're over-policing ourselves with this one but it's not a hill I'm gunna die on. Thanks!
